Test.assert_equals(song_decoder("AWUBBWUBC"), "A B C","WUB should be replaced by 1 space");
Test.assert_equals(song_decoder("AWUBWUBWUBBWUBWUBWUBC"), "A B C","multiples WUB should be replaced by only 1 space");
Test.assert_equals(song_decoder("WUBAWUBBWUBCWUB"), "A B C","heading or trailing spaces should be removed");
Test.assert_equals(song_decoder("RWUBWUBWUBLWUB"), "R L");
Test.assert_equals(song_decoder("WUBJKDWUBWUBWBIRAQKFWUBWUBYEWUBWUBWUBWVWUBWUB"), "JKD WBIRAQKF YE WV");
Test.assert_equals(song_decoder("WUBKSDHEMIXUJWUBWUBRWUBWUBWUBSWUBWUBWUBHWUBWUBWUB"), "KSDHEMIXUJ R S H");
Test.assert_equals(song_decoder("QWUBQQWUBWUBWUBIWUBWUBWWWUBWUBWUBJOPJPBRH"), "Q QQ I WW JOPJPBRH");
Test.assert_equals(song_decoder("WUBWUBOWUBWUBWUBIPVCQAFWYWUBWUBWUBQWUBWUBWUBXHDKCPYKCTWWYWUBWUBWUBVWUBWUBWUBFZWUBWUB"), "O IPVCQAFWY Q XHDKCPYKCTWWY V FZ");
Test.assert_equals(song_decoder("WUBYYRTSMNWUWUBWUBWUBCWUBWUBWUBCWUBWUBWUBFSYUINDWOBVWUBWUBWUBFWUBWUBWUBAUWUBWUBWUBVWUBWUBWUBJB"), "YYRTSMNWU C C FSYUINDWOBV F AU V JB");
Test.assert_equals(song_decoder("WUBKSDHEMIXUJWUBWUBRWUBWUBWUBSWUBWUBWUBHWUBWUBWUB"), "KSDHEMIXUJ R S H");
Test.assert_equals(song_decoder("AWUBWUBWUB"), "A");
Test.assert_equals(song_decoder("AWUBBWUBCWUBD"), "A B C D");
Test.assert_equals(song_decoder("WUBWWUBWUBWUBUWUBWUBBWUB"), "W U B");
Test.assert_equals(song_decoder("WUWUBBWWUBUB"), "WU BW UB");
Test.assert_equals(song_decoder("U"), "U");
Test.assert_equals(song_decoder("WUWUB"), "WU");
Test.assert_equals(song_decoder("UBWUB"), "UB");
Test.assert_equals(song_decoder("WUWUBUBWUBUWUB"), "WU UB U");
Test.assert_equals(song_decoder("WUBWWUBAWUB"), "W A");
Test.assert_equals(song_decoder("WUUUUU"), "WUUUUU");
Test.assert_equals(song_decoder("WUBWUBA"), "A");
